baseurl = "https://ehab-hassan.github.io/midori_archive/"
LanguageCode = "en"
title = "Midori"
theme = "landing"
contentdir = "content"
staticdir = "static"
publishDir = "docs"
relativeURLs = true
canonifyURLs = true

[permalinks]
    post = "/:filename"
