baseurl = "https://<ehab-hassan>.github.io/<midori_archive
>"
LanguageCode = "en"
title = "Midori"
theme = "landing"
contentdir = "content"
staticdir = "static"
publishdir = "en"
relativeURLs = true

[permalinks]
    post = "/:filename"
